# Generated by Django 3.1.3 on 2021-03-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20210301_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='campus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.campus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.cursus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_nummber',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
